## Full restore
auth:
  rootUser: root
  rootPassword: "${mongodb_root_user_password}"

restore:
  bucket_uri: ${bucket_uri}
  file_name: ${file_name}
  aws_default_region: ${s3_bucket_region}
  azure_storage_account_name: ${azure_storage_account_name}
  azure_storage_account_key: ${azure_storage_account_key}
  azure_container_name: ${azure_container_name}

annotations:
  ${annotations}

bucket_provider_type: ${bucket_provider_type}
